version: '3.9'
services:
  postgres:
    image: postgis/postgis:16-3.4-alpine
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
