name: Integration tests
run-name: Running integration tests
on: [push]
jobs:
  Postgres:
    runs-on: ubuntu-latest
    container: golang:1.22
    services:
      postgres:
        image: postgis/postgis:16-3.4-alpine
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - name: Run integration test
        run: PG_HOST=postgres make postgres-itest
  MySQL:
    runs-on: ubuntu-latest
    container: golang:1.22
    services:
      mysql:
        image: mysql:8.3
        env:
          MYSQL_ROOT_PASSWORD: mysql
        build_args: "--sql_mode=\"\""
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - name: Run integration test
        run: MYSQL_HOST=mysql make mysql-itest
