name: Integration tests
run-name: Running integration tests
on: [push]
jobs:
  container-job:
    runs-on: ubuntu-latest
    container: golang:1.22
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - name: Run integration test
        run: PG_HOST=postgres make itest
