name: Go checks

on: [push]

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Download dependencies
        run: go mod download

      - name: Install antlr
        run: |
          curl -O https://www.antlr.org/download/antlr-4.13.2-complete.jar
          echo "ANTLR_JAR=$(pwd)/antlr-4.13.2-complete.jar" >> $GITHUB_ENV

      - name: Generate antlr files
        run: make gh_antlr
        env:
            ANTLR: java -jar ${{ env.ANTLR_JAR }}

      - name: Run vet
        run: make vet

      - name: Run staticcheck
        env:
          SC_VERSION: "2024.1.1"
        run: |
          SC_URL="https://github.com/dominikh/go-tools/releases/download/$SC_VERSION/staticcheck_linux_amd64.tar.gz"
          wget -q ${SC_URL} -O - | tar -xzf - --strip-components 1 -C /usr/local/bin staticcheck/staticcheck
          make static

      - name: Run tests + race condition check
        run: make race

      - name: Check Go files are properly formatted
        run: test -z $(gofmt -l .)
