name: Integration tests

on: [push]

jobs:
  Postgres:
    runs-on: ubuntu-24.04
    container: golang:1.23
    services:
      postgres:
        image: postgis/postgis:16-3.4-alpine
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - name: Run integration test
        run: PG_HOST=postgres make postgres-itest

  MSSQL:
    runs-on: ubuntu-24.04
    container: golang:1.23
    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: yourStrong!Password
# TODO: Add healthcheck for MSSQL
# I spent a bunch of time and couldn't get it to work for GHA (it works for docker-compose)
# It also runs fine without it, but we should try to get this added.
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - name: Wait for 5 seconds
        run: sleep 5
      - name: Run integration test
        run: MSSQL_HOST=mssql make mssql-itest

  MySQL:
    runs-on: ubuntu-24.04
    container: golang:1.23
    services:
      mysql:
        image: mysql:8.3
        env:
          MYSQL_ROOT_PASSWORD: mysql
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - name: Run integration test
        run: MYSQL_HOST=mysql make mysql-itest

  MongoDB:
    runs-on: ubuntu-24.04
    container: golang:1.23
    services:
      mongo:
        image: mongo:7.0
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - name: Run integration test
        run: MONGO_HOST=mongo make mongo-itest
